#!/usr/pkg/bin/bash
echo "Content-type: text/html; charset:UTF-8;"
echo ""
echo "<!DOCTYPE html>"
echo "  <!-- Coding by CodingLab | www.codinglabweb.com -->"
echo "<html lang='en'>"
echo "<head>"
echo "    <meta charset='UTF-8'>"
echo "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>"
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
echo "    "
echo "    <!----======== CSS ======== -->"
echo "    <link rel='stylesheet' href='style.css'>"
echo "    "
echo "    <!----===== Boxicons CSS ===== -->"
echo "    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>"
echo "    "
echo "    <!--<title>Dashboard Sidebar Menu</title>--> "
echo "</head>"
echo "<style>"
echo "    /* Google Font Import - Poppins */"
echo "@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');"
echo "*{"
echo "    margin: 0;"
echo "    padding: 0;"
echo "    box-sizing: border-box;"
echo "    font-family: 'Poppins', sans-serif;"
echo "}"
echo ""
echo ":root{"
echo "    /* ===== Colors ===== */"
echo "    --body-color: #E4E9F7;"
echo "    --sidebar-color: #FFF;"
echo "    --primary-color: #695CFE;"
echo "    --primary-color-light: #F6F5FF;"
echo "    --toggle-color: #DDD;"
echo "    --text-color: #707070;"
echo ""
echo "    /* ====== Transition ====== */"
echo "    --tran-03: all 0.2s ease;"
echo "    --tran-03: all 0.3s ease;"
echo "    --tran-04: all 0.3s ease;"
echo "    --tran-05: all 0.3s ease;"
echo "}"
echo ""
echo "body{"
echo "    min-height: 100vh;"
echo "    background-color: var(--body-color);"
echo "    transition: var(--tran-05);"
echo "}"
echo ""
echo "::selection{"
echo "    background-color: var(--primary-color);"
echo "    color: #fff;"
echo "}"
echo ""
echo "body.dark{"
echo "    --body-color: #18191a;"
echo "    --sidebar-color: #242526;"
echo "    --primary-color: #3a3b3c;"
echo "    --primary-color-light: #3a3b3c;"
echo "    --toggle-color: #fff;"
echo "    --text-color: #ccc;"
echo "}"
echo ""
echo "/* ===== Sidebar ===== */"
echo " .sidebar{"
echo "    position: fixed;"
echo "    top: 0;"
echo "    left: 0;"
echo "    height: 100%;"
echo "    width: 250px;"
echo "    padding: 10px 14px;"
echo "    background: var(--sidebar-color);"
echo "    transition: var(--tran-05);"
echo "    z-index: 100;  "
echo "}"
echo ".sidebar.close{"
echo "    width: 88px;"
echo "}"
echo ""
echo "/* ===== Reusable code - Here ===== */"
echo ".sidebar li{"
echo "    height: 50px;"
echo "    list-style: none;"
echo "    display: flex;"
echo "    align-items: center;"
echo "    margin-top: 10px;"
echo "}"
echo ""
echo ".sidebar header .image,"
echo ".sidebar .icon{"
echo "    min-width: 60px;"
echo "    border-radius: 6px;"
echo "}"
echo ""
echo ".sidebar .icon{"
echo "    min-width: 60px;"
echo "    border-radius: 6px;"
echo "    height: 100%;"
echo "    display: flex;"
echo "    align-items: center;"
echo "    justify-content: center;"
echo "    font-size: 20px;"
echo "}"
echo ""
echo ".sidebar .text,"
echo ".sidebar .icon{"
echo "    color: var(--text-color);"
echo "    transition: var(--tran-03);"
echo "}"
echo ""
echo ".sidebar .text{"
echo "    font-size: 17px;"
echo "    font-weight: 500;"
echo "    white-space: nowrap;"
echo "    opacity: 1;"
echo "}"
echo ".sidebar.close .text{"
echo "    opacity: 0;"
echo "}"
echo "/* =========================== */"
echo ""
echo ".sidebar header{"
echo "    position: relative;"
echo "}"
echo ""
echo ".sidebar header .image-text{"
echo "    display: flex;"
echo "    align-items: center;"
echo "}"
echo ".sidebar header .logo-text{"
echo "    display: flex;"
echo "    flex-direction: column;"
echo "}"
echo "header .image-text .name {"
echo "    margin-top: 2px;"
echo "    font-size: 18px;"
echo "    font-weight: 600;"
echo "}"
echo ""
echo "header .image-text .profession{"
echo "    font-size: 16px;"
echo "    margin-top: -2px;"
echo "    display: block;"
echo "}"
echo ""
echo ".sidebar header .image{"
echo "    display: flex;"
echo "    align-items: center;"
echo "    justify-content: center;"
echo "}"
echo ""
echo ".sidebar header .image img{"
echo "    width: 40px;"
echo "    border-radius: 6px;"
echo "}"
echo ""
echo ".sidebar header .toggle{"
echo "    position: absolute;"
echo "    top: 50%;"
echo "    right: -25px;"
echo "    transform: translateY(-50%) rotate(180deg);"
echo "    height: 25px;"
echo "    width: 25px;"
echo "    background-color: var(--primary-color);"
echo "    color: var(--sidebar-color);"
echo "    border-radius: 50%;"
echo "    display: flex;"
echo "    align-items: center;"
echo "    justify-content: center;"
echo "    font-size: 22px;"
echo "    cursor: pointer;"
echo "    transition: var(--tran-05);"
echo "}"
echo ""
echo "body.dark .sidebar header .toggle{"
echo "    color: var(--text-color);"
echo "}"
echo ""
echo ".sidebar.close .toggle{"
echo "    transform: translateY(-50%) rotate(0deg);"
echo "}"
echo ""
echo ".sidebar .menu{"
echo "    margin-top: 40px;"
echo "}"
echo ""
echo ".sidebar li a{"
echo "    list-style: none;"
echo "    height: 100%;"
echo "    background-color: transparent;"
echo "    display: flex;"
echo "    align-items: center;"
echo "    height: 100%;"
echo "    width: 100%;"
echo "    border-radius: 6px;"
echo "    text-decoration: none;"
echo "    transition: var(--tran-03);"
echo "}"
echo ""
echo ".sidebar li a:hover{"
echo "    background-color: var(--primary-color);"
echo "}"
echo ".sidebar li a:hover .icon,"
echo ".sidebar li a:hover .text{"
echo "    color: var(--sidebar-color);"
echo "}"
echo "body.dark .sidebar li a:hover .icon,"
echo "body.dark .sidebar li a:hover .text{"
echo "    color: var(--text-color);"
echo "}"
echo ""
echo ".sidebar .menu-bar{"
echo "    height: calc(100% - 55px);"
echo "    display: flex;"
echo "    flex-direction: column;"
echo "    justify-content: space-between;"
echo "    overflow-y: scroll;"
echo "}"
echo ".menu-bar::-webkit-scrollbar{"
echo "    display: none;"
echo "}"
echo ".sidebar .menu-bar .mode{"
echo "    border-radius: 6px;"
echo "    background-color: var(--primary-color-light);"
echo "    position: relative;"
echo "    transition: var(--tran-05);"
echo "}"
echo ""
echo ".menu-bar .mode .sun-moon{"
echo "    height: 50px;"
echo "    width: 60px;"
echo "}"
echo ""
echo ".mode .sun-moon i{"
echo "    position: absolute;"
echo "}"
echo ".mode .sun-moon i.sun{"
echo "    opacity: 0;"
echo "}"
echo "body.dark .mode .sun-moon i.sun{"
echo "    opacity: 1;"
echo "}"
echo "body.dark .mode .sun-moon i.moon{"
echo "    opacity: 0;"
echo "}"
echo ""
echo ".menu-bar .bottom-content .toggle-switch{"
echo "    position: absolute;"
echo "    right: 0;"
echo "    height: 100%;"
echo "    min-width: 60px;"
echo "    display: flex;"
echo "    align-items: center;"
echo "    justify-content: center;"
echo "    border-radius: 6px;"
echo "    cursor: pointer;"
echo "}"
echo ".toggle-switch .switch{"
echo "    position: relative;"
echo "    height: 22px;"
echo "    width: 40px;"
echo "    border-radius: 25px;"
echo "    background-color: var(--toggle-color);"
echo "    transition: var(--tran-05);"
echo "}"
echo ""
echo ".switch::before{"
echo "    content: '';"
echo "    position: absolute;"
echo "    height: 15px;"
echo "    width: 15px;"
echo "    border-radius: 50%;"
echo "    top: 50%;"
echo "    left: 5px;"
echo "    transform: translateY(-50%);"
echo "    background-color: var(--sidebar-color);"
echo "    transition: var(--tran-04);"
echo "}"
echo ""
echo "body.dark .switch::before{"
echo "    left: 20px;"
echo "}"
echo ""
echo ".home{"
echo "    position: relative;"
echo "    top: 0;"
echo "    top: 0;"
echo "    left: 250px;"
echo "    height: 100vh;"
echo "    width: calc(100% - 250px);"
echo "    background-color: var(--body-color);"
echo "    transition: var(--tran-05);"
echo "}"
echo ".home .text{"
echo "    font-size: 30px;"
echo "    font-weight: 500;"
echo "    color: var(--text-color);"
echo "    padding-left: 15px;"
echo "}"
echo ""
echo ".sidebar.close ~ .home{"
echo "    left: 78px;"
echo "    height: 100vh;"
echo "    width: calc(100% - 78px);"
echo "}"
echo "body.dark .home .text{"
echo "    color: var(--text-color);"
echo "}"
echo ".frames{"
echo "    position: absolute;"
echo "    padding-left: 50px;"
echo "    width: 100%;"
echo "    height: 100%;"
echo "}"
echo ""
echo ".so{"
echo "    padding-left: 50px;"
echo "}"
echo ".container {"
echo "  position: relative;"
echo "  width: 100%;"
echo "  overflow: hidden;"
echo "  padding-top: 100%; /* 1:1 Aspect Ratio */"
echo "}"
echo ""
echo ".responsive-iframe {"
echo "  position: absolute;"
echo "  top: 0;"
echo "  left: 10px;"
echo "  bottom: 0;"
echo "  right: 0;"
echo "  width: 75%;"
echo "  height: 100%;"
echo "  border: none;"
echo "}"
echo ""
echo ".text2{"
echo "    font-size: 10px;"
echo "    font-weight: 500;"
echo "    color: var(--text-color);"
echo "    margin-left: 15px;"
echo "}"
echo "</style>"
echo "<body>"
echo "    "
echo "    <nav class='sidebar close'>"
echo "        <header>"
echo "            <div class='image-text'>"
echo "                <span class='image'>"
echo "                    <!--<img src='logo.png' alt=''>-->"
echo "                </span>"
echo ""
echo "                <div class='text logo-text'>"
echo "                    <span class='name'>Jordi Gonzalez</span>"
echo "                    <span class='profession'>Web developer</span>"
echo "                </div>"
echo "            </div>"
echo ""
echo "            <i class='bx bx-chevron-right toggle'></i>"
echo "        </header>"
echo ""
echo "        <div class='menu-bar'>"
echo "            <div class='menu'>"
echo ""
echo "                <ul class='menu-links'>"
echo "                    <li class='nav-link'>"
echo "                        <a href='#1'>"
echo "                            <i class='bx bx-home-alt icon' ></i>"
echo "                            <span class='text nav-text'>ifconfig</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#2'>"
echo "                            <i class='bx bx-bar-chart-alt-2 icon' ></i>"
echo "                            <span class='text nav-text'>neofetch</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#3'>"
echo "                            <i class='bx bx-bell icon'></i>"
echo "                            <span class='text nav-text'>dns</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#4'>"
echo "                            <i class='bx bx-pie-chart-alt icon' ></i>"
echo "                            <span class='text nav-text'>w</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#5'>"
echo "                            <i class='bx bx-heart icon' ></i>"
echo "                            <span class='text nav-text'>gateway</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#6'>"
echo "                            <i class='bx bx-wallet icon' ></i>"
echo "                            <span class='text nav-text'>Contenido de resolv.conf</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#7'>"
echo "                            <i class='bx bx-wallet-alt icon' ></i>"
echo "                            <span class='text nav-text'>df -h</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#8'>"
echo "                            <i class='bx bx-bug-alt icon' ></i>"
echo "                            <span class='text nav-text'>hostname</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#9'>"
echo "                            <i class='bx bx-award icon' ></i>"
echo "                            <span class='text nav-text'>version del kernel</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#10'>"
echo "                            <i class='bx bx-stopwatch icon' ></i>"
echo "                            <span class='text nav-text'>version del sistema operativo</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#11'>"
echo "                            <i class='bx bx-bowl-hot icon' ></i>"
echo "                            <span class='text nav-text'>nmap localhost</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                    <li class='nav-link'>"
echo "                        <a href='#12'>"
echo "                            <i class='bx bx-bowl-rice icon' ></i>"
echo "                            <span class='text nav-text'>ps $$</span>"
echo "                        </a>"
echo "                    </li>"
echo ""
echo "                </ul>"
echo "            </div>"
echo ""
echo "            <div class='bottom-content'>"
echo ""
echo "                <li class='mode'>"
echo "                    <div class='sun-moon'>"
echo "                        <i class='bx bx-moon icon moon'></i>"
echo "                        <i class='bx bx-sun icon sun'></i>"
echo "                    </div>"
echo "                    <span class='mode-text text'>Dark mode</span>"
echo ""
echo "                    <div class='toggle-switch'>"
echo "                        <span class='switch'></span>"
echo "                    </div>"
echo "                </li>"
echo "                "
echo "            </div>"
echo "        </div>"
echo ""
echo "    </nav>"
echo "    <section class='home' id='1'>"
echo "        <div class='text'>Ifconfig</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: ifconfig</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/ifconfig.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='2'>"
echo "        <div class='text'>neofetch</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: nanofetch --stdout</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/neofetch.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='3'>"
echo "        <div class='text'>dns</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: cat /etc/resolv.conf | grep nameserver</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/dns.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='4'>"
echo "        <div class='text'>W</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: w</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/w.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo "    <section class='home' id='5'>"
echo "        <div class='text'>gateway</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: netstat -rn</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/gateway.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='6'>"
echo "        <div class='text'>Contenido Resolv</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: Cat /etc/resolv.conf</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/resolv.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='7'>"
echo "        <div class='text'>df -h</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: df -h</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/dfh.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='8'>"
echo "        <div class='text'>Hostname</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: hostname</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/hostname.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='9'>"
echo "        <div class='text'>Version del Kernel</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: Uname -r</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/kernel.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='10'>"
echo "        <div class='text'>Sistema operativo</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: uname -a</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/so.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='11'>"
echo "        <div class='text'>Nmap localhost</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: nmap localhost</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/nmplhst.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo ""
echo "    <section class='home' id='12'>"
echo "        <div class='text'>Ps $$</div>"
echo "        <hr>"
echo "        <div class='text2'>Datos:Jordi Augusto Gonzalez Quintal 5190-18-5206</div>"
echo "        <hr>"
echo "        <div class='text2'>Comando: ps $$</div>"
echo "        <hr>"
echo "        <div class='text2'>"
echo "            Sistema Operativo"
echo "            <br>"
echo "            <iframe src='/cgi-bin/parcial4/soinfo.cgi' frameborder='0' class='So'></iframe>"
echo "        </div>"
echo "        <hr>"
echo "        <div class='text2'>Resultado</div>"
echo "        <div class='container'>"
echo "            <iframe src='/cgi-bin/parcial4/ps.cgi' frameborder='0' class='responsive-iframe'></iframe>"
echo "        </div>"
echo "        "
echo "    </section>"
echo "   "
echo ""
echo "    <script>"
echo "        const body = document.querySelector('body'),"
echo "      sidebar = body.querySelector('nav'),"
echo "      toggle = body.querySelector('.toggle'),"
echo "      modeSwitch = body.querySelector('.toggle-switch'),"
echo "      modeText = body.querySelector('.mode-text');"
echo ""
echo ""
echo "        toggle.addEventListener('click' , () =>{"
echo "            sidebar.classList.toggle('close');"
echo "        })"
echo ""
echo ""
echo ""
echo "        modeSwitch.addEventListener('click' , () =>{"
echo "            body.classList.toggle('dark');"
echo "            "
echo "            if(body.classList.contains('dark')){"
echo "                modeText.innerText = 'Light mode';"
echo "            }else{"
echo "                modeText.innerText = 'Dark mode';"
echo "                "
echo "            }"
echo "        });"
echo "    </script>"
echo ""
echo "</body>"
echo "</html>"
echo ""